[[redirects]]
from = "/thank-you/*"
to = "/thank-you/:splat"
status = 200
force = false

[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Thank-you redirect (also works after POST)


[[redirects]]
  from = "/thank-you"
  to = "/?thank-you=1"
  status = 303
  force = true
